---
- name: Update web servers
  hosts: webservers
  become: yes
  remote_user: ubuntu

  tasks:
  - name: "install nginx"
    apt:
      name: ['nginx']
      state: latest

  - name: ufw enabled
    community.general.ufw:
      state: "enabled"
      policy: "deny"
      logging: "on"

  - name: Allowing access to port 80
    community.general.ufw:
      rule: allow
      port: '80'

  - name: Allowing access to port 22
    community.general.ufw:
      rule: allow
      port: '22'
